server:
  port: 8080
  servlet:
    context-path: /
spring:
  config:
    import: classpath:db.properties
  datasource:
    url: ${sist_url}
    username: ${sist_username}
    password: ${sist_password}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: oracle
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect 
        format_sql: true
        user_sql_comments: true   
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
  #ai:
    #google:
      #genai:
        #api-key:
jwt:
  secret: ${jwt_secret}
  access-token-expiration: 1800000       # 30분
  refresh-token-expiration: 1209600000   # 14일
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE